version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - yarn install
  build:
    commands:
      - echo Building the React app
      - yarn run build

artifacts:
  files:
    - '**/*'
    - appspec.yml
  base-directory: "./"

cache:
  paths:
    - "node_modules/**/*"