version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Building the React app
      - npm run build

artifacts:
  files:
    - '**/*'
    - appspec.yml
    - scripts/before_install.sh
    - scripts/install_dependencies.sh
    - scripts/start_server.sh
    - scripts/stop_server.sh
  base-directory: "./"

cache:
  paths:
    - "node_modules/**/*"